### ISSUE TITLE
Update and/or redirect links to visbrain modules

### ISSUE THREAD

**Issue by pausz** [EtienneCmb/visbrain#10]
Not sure you can update the links given in the article : 
https://www.frontiersin.org/articles/10.3389/fninf.2017.00060/full 

but you can probably update the links in the README  file and/or redirect the old pages to the new ones?  

For instance http://visbrain.org/sleep.html gives you a 404 
![not_found](https://user-images.githubusercontent.com/1563810/32878900-01d5d818-cafc-11e7-90d3-da3fc893d9d1.png)

**Comment by EtienneCmb** [comment]
ba9983b
