### ISSUE TITLE
Documentation (visbrain.org) 

### ISSUE THREAD

**Issue by sykesva** [EtienneCmb/visbrain#102]
Hi. For some reason, the official documentation site hasn't been working for a couple of days by now ('This site can’t be reached'). Any ideas on what happened and how soon it will be fixed? I also tried using VPN, didn't work as well.

**Comment by EtienneCmb** [comment]
Hi @cyberfag 

Yes I know, it's normal. There's with the service hosting the documentation. I've no idea when it's going to come back. Soon I'll say

**Comment by EtienneCmb** [comment]
website is back

**Comment by sykesva** [comment]
@EtienneCmb thank you :)
