### ISSUE TITLE
Issues with setup.py for pip >=10

### ISSUE THREAD

**Issue by akosv** [EtienneCmb/visbrain#15]
Hello,

A quick note. I had to change the following two import statements:

1) from pip.req import parse_requirements -> from pip._internal.req import parse_requirements
2) from pip.download import PipSession  # pylint:disable=E0611 -> from pip._internal.download import PipSession  # pylint:disable=E0611

in setup.py to make it work with pip v10.0.1

Thanks.

**Comment by EtienneCmb** [comment]
Hi @akosv , thanks for the feedback. Do you think you can propose a PR to fix it?

Thanks,

**Comment by EtienneCmb** [comment]
This issue should be solved. See c317c5f26ecf2a38dfa02fbd3805751388897ae3 and 6008f8b21ebdd5c447d7e959832824018d53ae5e
