### ISSUE TITLE
Please Help!!

### ISSUE THREAD

**Issue by Miriam5ht** [EtienneCmb/visbrain#16]
Every time I try to install visbrain I get this error. 

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2c_5bqh_/visbrain/

What can I do??

I'm no expert in python, but Im very interested in using the sleep software for my PhD thesis.

**Comment by EtienneCmb** [comment]
Hi @Miriam5ht ,

This issue is probably related to #15. You should be able to fix it using either :

- A version of pip < 10 : `pip install pip==9.0.3`
- Install visbrain in [develop mode](http://visbrain.org/#develop-mode)

let me known :)

**Comment by Miriam5ht** [comment]
Thank you!!!
I installed pip 9.0.3 and had no problem installing visbrain. 
I'm very excited to start using it. :D
