### ISSUE TITLE
MEG inverse solution seems to be using the smoothing matrix badly

### ISSUE THREAD

**Issue by dmalt** [EtienneCmb/visbrain#19]
I'm talking about this [ example](http://visbrain.org/auto_examples/eeg_meg/meg_inverse_solution.html#sphx-glr-auto-examples-eeg-meg-meg-inverse-solution-py). The solution looked to me too ''grainy'', so I increased the number of smoothing steps to 15 and  the activation started to look completely f***** up:

![deepinscreenshot_ _20180731155054](https://user-images.githubusercontent.com/8067672/43460787-5442a646-94da-11e8-8fde-4b516d08e193.png)

I've looked into the source source code of  BrainObj.add_activation function and it seems to me this
line in brain_obj.py is to blame:
```
sm_data = data[sm_mat.col]
```
You should multiply the data by the smoothing matrix instead of indexing it.
I've managed to make a dirty fix for it work on my laptop. The solution now looks like this with the same 15 smoothing steps:
![deepinscreenshot_20180731155126](https://user-images.githubusercontent.com/8067672/43460824-769ddd6e-94da-11e8-9e06-4a8e9e48d5c3.png)

 I can create a pull request if you want me to.

**Comment by EtienneCmb** [comment]
Hello dima ! Glad to see you there :)

Awesome ! The current implementation has a render that is similar to the one in [pysurfer](https://pysurfer.github.io/auto_examples/plot_meg_inverse_solution.html#sphx-glr-auto-examples-plot-meg-inverse-solution-py) but yours is much better. Can you switch to the develop branch and make the PR? Because I made a lot of updates (colormap is now computed using 2D textures)

**Comment by EtienneCmb** [comment]
note that you'll need cython and the latest vispy version `pip install git+https://github.com/vispy/vispy.git`

**Comment by dmalt** [comment]
Salut, Etienne! Long time no see) Hope you're doing well!
Yes, sure, will do.
Yes, I've noticed that the smoothing matrix calculation is from pysurfer. I used it myself for another project. I've changed only what is done with it after it's calculated --- namely --- multiply the data array by it.
Awesome to see how visbrain matured. Great job!

**Comment by EtienneCmb** [comment]
Both hemispheres are always loaded.

**Comment by EtienneCmb** [comment]
Then, to display only the left or right hemisphere I use an `IndexBuffer` which is basically a loop over concerned vertices

**Comment by EtienneCmb** [comment]
#20
