### ISSUE TITLE
vispy version 0.5?

### ISSUE THREAD

**Issue by kevroy314** [EtienneCmb/visbrain#2]
I've noticed when installing this that you can't automatically get vispy 0.5. You have to install it via git. Also, after doing so, some things don't load (ColorBar from vispy.scene.visuals, for example). Is there a stable version of vispy that I can download to use this?

**Comment by kevroy314** [comment]
This seems to be resolved if you use python 3.5 instead of 2.7. Feel free to close the issue.

**Comment by EtienneCmb** [comment]
Yes I know there's some installation issues, especialy with vispy. If you've any python package installation experience, do you think you can contribute to improve it?

**Comment by kevroy314** [comment]
I think until vispy releases version 0.5 (which hopefully will be soon), your two options are to either downgrade your requirements to 0,4 (which I don't think works because you're using some 0.5 features) or install from git. Maybe just adding to the install instructions. Importantly, it seems like the way the imports are working with vispy, you need some python 3.5 features (though I'm not entirely sure why/which ones). This set of instructions for installing visbrain work well for me:

```
conda create --yes -n visbrain python=3.5 anaconda
activate visbrain
git clone https://github.com/EtienneCmb/visbrain.git visbrain
git clone https://github.com/vispy/vispy vispy
cd vispy
python setup.py install
cd ..\visbrain
pip install .
```

**Comment by EtienneCmb** [comment]
Great, i'll add your instructions to the doc. I think that the Colorbar class is the only need for vispy 0.5 some may be I can replace it. I also planned to update visbrain with pyqt5 but last time I tried it just failed to open the window.

**Comment by kevroy314** [comment]
Sorry, I forgot to add, the line that currently says "pip install ." needs the --no-deps flag to ignore the dependencies. So it should read:
`pip install . --no-deps
`

**Comment by kevroy314** [comment]
Just tried it out on a virtual machine in Windows 10. You also need:

`conda install --yes pyqt=4`

The default for conda right now is 5.6.0 which means you get an error running the examples.

So the full thing that worked on my VM was:

```
conda create --yes -n visbrain python=3.5 anaconda
activate visbrain
git clone https://github.com/EtienneCmb/visbrain.git visbrain
git clone https://github.com/vispy/vispy vispy
cd vispy
python setup.py install
cd ..\visbrain
pip install . --no-deps
conda install --yes pyqt=4
```

**Comment by EtienneCmb** [comment]
Hello ! Sorry i'm late. Thx for the installation recommendations the doc has been updated with your suggestion : http://etiennecmb.github.io/visbrain/index.html
I close the issue :+1:
