### ISSUE TITLE
Visbrain in IronPython

### ISSUE THREAD

**Issue by STREETKILLER007** [EtienneCmb/visbrain#21]
I am using Window 7, 64 bit version.

I am trying to implement visbrain using ironPython in Visual Studio 2017, framework 4.0.

below is my iron python environment :  
IronPython v2.7.8
IronPython.StdLib v2.7.8.1

This is the code that i am working on.

```
// create python engine
var myPythonEngine = Python.CreateEngine();

// create search path
var searchPaths = myPythonEngine.GetSearchPaths();

searchPaths.Add(@"D:\Python35\");
searchPaths.Add(@"D:\Python35\Scripts\");
searchPaths.Add(@"D:\Python35\Lib"); // python standard library
         
// set search path
myPythonEngine.SetSearchPaths(searchPaths);

// create scope to execute python code and get backs results from python code
var myScope = myPythonEngine.CreateScope();

// create the source
var mySource = myPythonEngine.CreateScriptSourceFromFile(@"testtopo.py");

// execute the scope
mySource.Execute(myScope);
```

testtopo.py only contains 2 lines of code, which is 

```
from visbrain import Topo

# Create a topoplot instance :
t = Topo()
```

But it pops out an error said 
**IronPython.Runtime.Exceptions.ImportException: 'No module named visbrain'**

Would like to know what have i miss out, so that i can solve this issue. Thank You.

**Comment by EtienneCmb** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/EtienneCmb/visbrain/issues/4 (installing visbrain), https://github.com/EtienneCmb/visbrain/issues/10 (Update and/or redirect links to visbrain modules), and https://github.com/EtienneCmb/visbrain/issues/17 (Hello I cant open visbrain  everytime i get same error ).

**Comment by STREETKILLER007** [comment]
solved by adding 2 line

```
searchPaths.Add(@"D:\Python35\DLLs");
searchPaths.Add(@"D:\Python35\lib\site-packages");
```

but after this 2 line, pops out another error, which is

```
Exception thrown: 'Microsoft.Scripting.SyntaxErrorException' in Microsoft.Dynamic.dll
An unhandled exception of type 'Microsoft.Scripting.SyntaxErrorException' occurred in Microsoft.Dynamic.dll
unexpected token 'exc_info'
```

**Comment by STREETKILLER007** [comment]
I had emailed iron python developers about this error.

According to http://visbrain.org
Visbrain is open source python 3 package.

According to the developer of iron python, they only support python 2 and are working
