### ISSUE TITLE
Hardware requirement for Visbrain

### ISSUE THREAD

**Issue by STREETKILLER007** [EtienneCmb/visbrain#23]
I read the documentation of Visbrain from http://visbrain.org/documentation.html

You just wrote the dependency.
I think it will be great if you can write down the hardware requirements for Visbrain in the documentation.

**Comment by EtienneCmb** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/EtienneCmb/visbrain/issues/4 (installing visbrain), https://github.com/EtienneCmb/visbrain/issues/21 (Visbrain in IronPython), https://github.com/EtienneCmb/visbrain/issues/22 (Visbrain in Pythonnet), https://github.com/EtienneCmb/visbrain/issues/10 (Update and/or redirect links to visbrain modules), and https://github.com/EtienneCmb/visbrain/issues/17 (Hello I cant open visbrain  everytime i get same error ).

**Comment by EtienneCmb** [comment]
I've never seen a Python package with hardware requirements and IMO it would be almost impossible to list them all...
