### ISSUE TITLE
OpenGL unrecognized on Linux

### ISSUE THREAD

**Issue by dmalt** [EtienneCmb/visbrain#3]
Description:
after installation and running
```
from visbrain import Brain
vb = Brain(a_template='B3')
```
I get the following error:

> 
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: i965_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: i965
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Unrecognized OpenGL version
Unrecognized OpenGL version

Apparently some libs are missing but quick forums search didn't get me anywhere.
And I installed pyopengl.

Did you have an issue like that?

**Comment by EtienneCmb** [comment]
I had it with my linux, at the beginning, when moving to PyQt5. I fix it with by updating to the latest PyQt5 and sip versions.

Can you try?

**Comment by dmalt** [comment]
I update everything and it solved the problem.
Thanks! I'll try to run some more examples.
