### ISSUE TITLE
Accept different decimal separator

### ISSUE THREAD

**Issue by skjerns** [EtienneCmb/visbrain#30]
In some countries (i.e. France and Germany), the comma is the decimal separator.
However, in most countries, a dot indicates the decimal.

Right now, my dots are just ignored and I create a filter of `8 Hz` instead of '0.8 Hz'.

What would be the best way to implement such options system wide? If you point me towards a good entry point I can see if I can implement it.

**Comment by EtienneCmb** [comment]
hi @skjerns 

I think this is a minor issue, even if I understand your point. This might be changed from the Qt designer

**Comment by skjerns** [comment]
The NUM-pad decimal separator will output a different character depending on the language setting (`.` or `,`). This makes the NUM-pad unusable for visbrain if using a dot-decimal setting.

I agree that it's a minor issue.
