### ISSUE TITLE
[Sleep] Channel amplitude max limited

### ISSUE THREAD

**Issue by skjerns** [EtienneCmb/visbrain#31]
Currently, the maximum channel amplitude is set to the maximum of the signal. However, in some cases (such as large monitors with clipped signals) it can be preferable to set the maximum channel amplitude (= the scaling) to a higher value (that means, decrease the displayed channel amplitudes).

Suggestion: Remove the upper limit of the maximum amplitude scaling.

I tried to look in the source where I can change this (i.e. `_PanAllAmpMax`), however, I could not find where the maximum value restriction is set (no call to `_PanAllAmpMax.setMaximum` anywhere).

**Comment by EtienneCmb** [comment]
Why would you like to have a smaller signal on the screen?

**Comment by skjerns** [comment]
Some of my recordings have quite low recording range: thi makes low amplitudes appear as massive, if they are not not rescaled. This becomes even more a problem if the window is maximized on a large screen.

Example:
![capture](https://user-images.githubusercontent.com/14980558/47219741-fea89a00-d3af-11e8-9360-b3f1de64d87e.PNG)

Most GUIs I worked with were allowing to rescale the signal as big/small as required. Would that be an idea here as well?

**Comment by skjerns** [comment]
Unforunately not, currently the rescaling is limited by the `['max']` of the channel. In my case, the physical `['max']` is denoted as 40.25 (second line). This means I can't set the signal 'smaller' than the middle line in the picture above (maximum amplitde is 40.25). I had to change some parameters in the source to allow a scaling to a maximum amplitude of 90 as in the third signal. Does this make sense? It might be a bit hard to understand what I mean, indeed.

**Comment by EtienneCmb** [comment]
Hi @skjerns , sorry for the delay. I think I finally got your point. It's true that the min and max of the GUI elements are defined using the min and max of the data (see this [function](https://github.com/EtienneCmb/visbrain/blob/master/visbrain/gui/sleep/interface/ui_elements/ui_panels.py#L307)). But we could allow the user to used values under the min or over the max. We just need to find a range.

**Comment by skjerns** [comment]
Why not leave it entirely up to the user, but set a reasonable standard value?
As the user will see immediate feedback on his actions, it's their responsibility to scale it to infinity.

**Comment by EtienneCmb** [comment]
At least we could set `10. * min()` and `10. * max()` this should provide a sufficient range

**Comment by skjerns** [comment]
sounds reasonable!

**Comment by EtienneCmb** [comment]
Hello @skjerns ,

Sorry for the delay. I recently push a modification (cb36e8a21a4fa0745a43604140718d1312d31a66) to limit channel amplitudes to (10 * min, 10 * max). This should fix your issue?

**Comment by skjerns** [comment]
it does :) thanks a lot!
