### ISSUE TITLE
installing visbrain

### ISSUE THREAD

**Issue by EhsanTadayon** [EtienneCmb/visbrain#4]
Hi, 

I'm trying to install visbrain but I get this error:

Could not find a version that satisfies the requirement pyqt5 (from visbrain) (from versions: )
No matching distribution found for pyqt5 (from visbrain)

I am using anaconda python2. I couldn't install pyqt5 through pip but I installed it using conda. 

thanks.

**Comment by EtienneCmb** [comment]
Hello ! 

So pyqt 5 is installed? If you open a python interpreter, you can import PyQt5? 

I just update visbrain to be compatible with pyqt5 so you might have some bugs. I also recommend to use python 3.

**Comment by EhsanTadayon** [comment]
Hi, 

Thanks. Converting to Python3 actually solved the problem.
