### ISSUE TITLE
using visbrain with x11 forwarding and xming

### ISSUE THREAD

**Issue by kgerman73** [EtienneCmb/visbrain#46]
I get the following error trying to import the visbrain modules.  This is a RHEL7 workstation which I ssh into using putty and forward x11 to xming.  Is visbrain not compatible with xming?

#-> python3
Python 3.6.8 (default, Apr 25 2019, 21:02:35)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> from visbrain.gui import Brain
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted

#-> python3 -m pip list | egrep -i 'numpy|matplot|vispy|pyqt5|pyopengl|pillow|visbrain'
matplotlib      2.1.0
numpy           1.16.4
Pillow          6.0.0
PyOpenGL        3.1.0
PyQt5           5.12.2
PyQt5-sip       4.19.17
visbrain        0.4.4
vispy           0.5.3

Thanks,
Keith

**Comment by kgerman73** [comment]
I added the path to the libxkbcommon libraries and now I get a different error.

# python3
Python 3.6.8 (default, Apr 25 2019, 21:02:35)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from visbrain.gui import Sleep
qt.qpa.xcb: X server does not support XInput 2
failed to get the current screen resources
>>> WARNING: QXcbConnection: XCB error: 1 (BadRequest), sequence: 163, resource id: 90, major code: 130 (Unknown), minor code: 47
WARNING: QXcbConnection: XCB error: 170 (Unknown), sequence: 176, resource id: 90, major code: 146 (Unknown), minor code: 20

**Comment by EtienneCmb** [comment]
Hi @kgerman73 ,

Unfortunately, I've never tested such configuration. But visbrain is tested on a server (travis). May be take a look at the [configuration file](https://github.com/EtienneCmb/visbrain/blob/master/.travis.yml)

**Comment by EtienneCmb** [comment]
I might also comes from the PyQt version. I recommend to try out version <5.12 (`pip install --retries 3 "pyqt5<5.12.0"`). You can check the version using : 
```python
from PyQt5.QtCore import QT_VERSION_STR
from PyQt5.Qt import PYQT_VERSION_STR
from sip import SIP_VERSION_STR

print("Qt version:", QT_VERSION_STR)
print("SIP version:", SIP_VERSION_STR)
print("PyQt version:", PYQT_VERSION_STR)
```

**Comment by kgerman73** [comment]
Downgraded PyQt5, now get a different error.

#-> python3 -m pip list | grep PyQt5
PyQt5           5.11.3
PyQt5-sip       4.19.17

# python3
Python 3.6.8 (default, Apr 25 2019, 21:02:35)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> from visbrain.gui import Brain
failed to get the current screen resources
Could not initialize GLX
Aborted

**Comment by EtienneCmb** [comment]
Does the travis file help?

**Comment by kgerman73** [comment]
Not with Xming but I tried VcXsrv  and it works.  Thanks for your help.

**Comment by EtienneCmb** [comment]
It might be interesting for others to describe the steps you did . Should I closed the issue?

**Comment by kgerman73** [comment]
I went through the travis config file and installed the python packages listed in the "install" section and downgraded PyQt5 to 5.11.3 but that didn't help.  I was googling the error messages and came across a thread that said VcXsrv when Xming didn't so I gave it a shot.  Installed with default options and worked like a charm.  Please feel free to close the issue.

https://sourceforge.net/projects/vcxsrv/

HTH,
Keith
