### ISSUE TITLE
ImportError: cannot import name 'imresize' from 'scipy.misc'

### ISSUE THREAD

**Issue by miao-cao** [EtienneCmb/visbrain#49]
Using Scipy=1.3.0, which has removed function imresize from scipy.misc. 

Any chances for a quick fix without downgrading to <=1.2.0, because using mne-python virtual env and better off not change version numbers?

Thanks very much.

**Comment by jasmainak** [comment]
what version of `visbrain` are you using? maybe you need to upgrade to development version ...

**Comment by miao-cao** [comment]
Using visbrain 0.4.4.

Just did this: pip install git+https://github.com/EtienneCmb/visbrain.git

, but still giving the same error.

**Comment by InteGerard** [comment]
To fix the import error for now:
Use a fresh Python 3.6 Env.
pip install scipy==1.1.0

**Comment by EtienneCmb** [comment]
Hi @miao-cao @InteGerard 

I made a new release of visbrain this morning, import issues should now be solved.

Thanks for your feedbacks

**Comment by miao-cao** [comment]
> 
> 
> Hi @miao-cao @InteGerard
> 
> I made a new release of visbrain this morning, import issues should now be solved.
> 
> Thanks for your feedbacks

Yes, confirm that the error has been fixed. Thanks.
