### ISSUE TITLE
The cmap doesn't work for an example code

### ISSUE THREAD

**Issue by devangini27** [EtienneCmb/visbrain#51]
I am trying to run the demo code for cross-section and volume control: http://visbrain.org/auto_examples/gui_brain/01_cross_sections_and_volume.html. However, I see the cross-sections in white as shown in the image.

![Screenshot from 2019-09-27 17-41-48](https://user-images.githubusercontent.com/3685200/65803915-1ce55100-e14e-11e9-8344-5ad2893aca35.png)

Could you please help me?

**Comment by EtienneCmb** [comment]
Hi @devangini27 , indeed, the `cmap` argument has been removed, this is now only active when adding activations.
