### ISSUE TITLE
Load Annotation with custom brain 

### ISSUE THREAD

**Issue by iPsych** [EtienneCmb/visbrain#59]
Annotation with parcellize comment shows strange result. I guess it is somehow related faces # just changed above? when annotation file loaded single hemisphere, just yellow brain or yellow brain with one region shows in purple.

```
b_obj.parcellize(lh_annot, hemisphere='left')
b_obj.parcellize(rh_annot, hemisphere='right')

```
Tested both

```
b_obj.parcellize(lh_annot)
b_obj.parcellize(rh_annot)
```
and

```
b_obj.parcellize(lh_annot, hemisphere='left')
b_obj.parcellize(rh_annot, hemisphere='right')
```
but the only difference was the warning.

> WARNING | left hemisphere(s) inferred from filename
> WARNING | right hemisphere(s) inferred from filename

It seems the code load annotation properly, but cannot map it properly.
If I re-call the parcelize code as below, both hemisphere shows the proper segmented regions, but with changed color.

```
b_obj.parcellize(lh_annot, hemisphere='left')
b_obj.parcellize(rh_annot, hemisphere='right')
b_obj.parcellize(rh_annot, hemisphere='right')
```
![Screen Shot 2020-02-03 at 10 20 15 PM](https://user-images.githubusercontent.com/28276515/73738798-773f8f80-4788-11ea-9caa-13c35d6feecd.png)

**Comment by iPsych** [comment]
It turned out that the issue was very special to custom (BN_Atlas) annotation file, which contains the label information for both hemisphere in each .annot file.

**Comment by EtienneCmb** [comment]
oh I see, thanks for the feedback.

++
