### ISSUE TITLE
Add EGI MFF reading capability

### ISSUE THREAD

**Issue by christian-oreilly** [EtienneCmb/visbrain#6]
As already explicit in the title. 

Code can be inspired from other package now providing this capability:
- https://github.com/gpiantoni/phypno/blob/master/phypno/ioeeg/egimff.py
- https://github.com/mne-tools/mne-python/blob/master/mne/io/egi/egimff.py

**Comment by EtienneCmb** [comment]
Hey @christian-oreilly 

We now use MNE-python to load EGI and MFF files. Lazy loading will still need improvements but this issue might be set to solved?

**Comment by christian-oreilly** [comment]
Hi @EtienneCmb 

Yes, I guess the core feature that was required is now implemented. Let's close this ticket and if the current implementation has some limitations that need to be addressed, lets create new tickets describing these specific limitations as they are identified.
