### ISSUE TITLE
Is it possible to merge multiple BrainObj?

### ISSUE THREAD

**Issue by iPsych** [EtienneCmb/visbrain#60]
Is it possible to merge multiple BrainObj?
For example, build two separate BrainObj (Left and Right hemisphere) and merge them, or several Objs from label volumes.

**Comment by EtienneCmb** [comment]
Yes, it should be possible using the [`SceneObj`](http://visbrain.org/generated/visbrain.objects.SceneObj.html#visbrain.objects.SceneObj), which is made to superimpose objects. Something like that :
```python
sc = SceneObj()
b_obj_1 = BrainObj('custom_1', ...)
b_obj_2 = BrainObj('custom_2', ...)

sc.add_to_subplot(b_obj_1)
sc.add_to_subplot(b_obj_2)

sc.preview()
```

See [examples](http://visbrain.org/generated/visbrain.objects.SceneObj.html#examples-using-visbrain-objects-sceneobj) using the scene

**Comment by iPsych** [comment]
Thanks. I am wondering merge objects in GUI.
It seems not possible to put multiple BrainObj in Brain.

```
from visbrain.gui import Brain
vb = Brain(brain_obj=b_obj)
vb.show()
```

**Comment by EtienneCmb** [comment]
Yes, the GUI only supports a single brain object
