### ISSUE TITLE
Loading vertex directly as ROI

### ISSUE THREAD

**Issue by iPsych** [EtienneCmb/visbrain#61]
Is it possible to load vertex (i.e. pre-generated .vtk file) directly as ROI?

I saw below line in roi_obj.py, and believe it's the starting point.
Can I add some brief define or class to do so?
The vert and faces are already loaded, so, just integration is required.
 
`vert, faces, data = np.array([]), np.array([]), np.array([])`

**Comment by EtienneCmb** [comment]
@iPsych , no it's not possible to load vtk files as ROI. Feel free to submit a PR
