### ISSUE TITLE
Change font by vispy 

### ISSUE THREAD

**Issue by iPsych** [EtienneCmb/visbrain#62]
In vispy, text object is declared like below.
```
    def __init__(self, text=None, color='black', bold=False,
                 italic=False, face='OpenSans', font_size=12, pos=[0, 0, 0],
                 rotation=0., anchor_x='center', anchor_y='center',
                 method='cpu', font_manager=None):
```

I can see the bold, italic, and font_size in visbrain, but is there any connection to **'face'** which might allow the font change in the canvas using system font?

**Comment by EtienneCmb** [comment]
@iPsych please, use the gitter to ask your questions because this is not an issue.
