### ISSUE TITLE
Add .rec loading capability

### ISSUE THREAD

**Issue by Neergaard** [EtienneCmb/visbrain#7]
As described in title. 

A lot of sleep studies are collected in .rec file format - would be excellent to have the opportunity to open this in the Sleep tool!

**Comment by raphaelvallat** [comment]
Thank you for this suggestion! I am not familiar with the .rec data format but from what I have understood it's basically an EDF file with the .rec extension (see for example here: https://www.physionet.org/physiobank/database/sleep-edf/). Do you agree or were you thinking of a totally different file format (and if so could you please send us an example dataset) ? Thanks again ! Raphaël

**Comment by Neergaard** [comment]
I think you are correct, that it is basically correct. So it would technically still be supported by the Sleep GUI?

Thank you for your quick reply!

On Oct 3, 2017, at 22:42, Raphael Vallat <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you for this suggestion! I am not familiar with the .rec data format but from what I have understood it's basically an EDF file with the .rec extension (see for example here: https://www.physionet.org/physiobank/database/sleep-edf/). Do you agree or were you thinking of a totally different file format (and if so could you please send us an example dataset) ? Thanks again ! Raphaël

**Comment by EtienneCmb** [comment]
Hello @Neergaard , can you share a small dataset so that we can try if your EDF loading function is also able to load you .rec file? If @raphaelvallat is right, we could make some adjustments !

Thanks for your feedback,

**Comment by Neergaard** [comment]
Well, you can use the ISRUC database available at http://sleeptight.isr.uc.pt/ISRUC_Sleep/

All the data there is in .rec format.

Thanks!

On 04 Oct 2017, at 07:30, Etienne Combrisson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @Neergaard<https://github.com/neergaard> , can you share a small dataset so that we can try if your EDF loading function is also able to load you .rec file? If @raphaelvallat<https://github.com/raphaelvallat> is right, we could make some adjustments !

Thanks for your feedback,

**Comment by EtienneCmb** [comment]
Ok, so I downloaded the first dataset and make some small adjustments. @raphaelvallat was right, the EDF function was able to load the .rec file. See b3243537623347e2725e01f3e5bbced153288d15.

Hope it will works for you too !

![screenshot](https://user-images.githubusercontent.com/15892073/31187221-83884f22-a931-11e7-8327-a5897dc12b57.png)

**Comment by raphaelvallat** [comment]
Hi @Neergaard ! We released today a new stable version which allows, among many other improvements, the native support of .rec files. You can see an example here: [http://visbrain.org/auto_examples/sleep/load_rec.html#sphx-glr-auto-examples-sleep-load-rec-py](http://visbrain.org/auto_examples/sleep/load_rec.html#sphx-glr-auto-examples-sleep-load-rec-py)
Hope this helps!
