### ISSUE TITLE
Mouse clicking to zoom out the picture

### ISSUE THREAD

**Issue by zhengliuer** [EtienneCmb/visbrain#91]
![image](https://user-images.githubusercontent.com/65115609/108458080-d64a4680-72ae-11eb-9f10-bd34ea02cb7f.png)
Does visbrain support mouse clicking? Like when I click the picture of the electrode, it will zoom out.

**Comment by EtienneCmb** [comment]
By default no, because mouse click (and scroll) are used for the turntable camera. That being said, but you can probably configure your own mouse events (like click and double click) using [vispy](https://vispy.org/api/vispy.app.canvas.html?highlight=click)

**Comment by zhengliuer** [comment]
> By default no, because mouse click (and scroll) are used for the turntable camera. That being said, but you can probably configure your own mouse events (like click and double click) using [vispy](https://vispy.org/api/vispy.app.canvas.html?highlight=click)

Thank U! I'll give it  a try
